### ISSUE TITLE
Blocking Logins

### ISSUE THREAD

**Issue by tylerxc0m** [skorokithakis/django-tokenauth#3]
Hi @skorokithakis & @sirodoht 

Thanks for developing this Django package, for a novice I've found it really simple to get working and the functionality is great.

I have one issue that I was hoping you could assist with. Ideally it would be great if I could disallow deactivated users from logging in. Is this something I can configure with the TOKENAUTH_NORMALIZE_EMAIL option?

Worst case if this isn't possible if you could point me in the direction to only allow already registered users to login? for example no new account creations.

Appreciate the package and hopefully your assistance. 

PS Merry Christmas!

**Comment by skorokithakis** [comment]
Merry Christmas to you too! Unfortunately this isn't possible with NORMALIZE_EMAIL because it doesn't get passed the user object, but this is a good feature that should be added. I will look into how it can be supported, probably by another setting.

Give me a shout if I haven't gotten to it in a few days (or feel free to file a PR). Thanks for the request!

**Comment by tylerxc0m** [comment]
Hey @skorokithakis 

Thanks for the quick reply - Appreciate you looking into this :)

**Comment by skorokithakis** [comment]
This has been added in **398c694e39d20e678553a8a6a192cfdfcc7631c9**, can you see if it works well and let me know, @tylerxc0m?

**Comment by tylerxc0m** [comment]
Hi @skorokithakis,

I’ve started testing the change and it’s looking good from what I’ve seen so far. I have run into one issue with additional users being created even though they’re already added in as a user. 

I want to do a bit more testing on my side of things (dev environment is pretty janky at the moment).

Many thanks for the fix! I really appreciate it.
